# Default configuration for NavierFlow

experiment_name: "default_experiment"
seed: 42

# Model configuration
model:
  model_type: "pinn"  # One of: pinn, mesh_optimizer, anomaly_detector
  name: "default_model"
  version: "1.0.0"
  description: "Default NavierFlow model configuration"
  
  # Training settings
  batch_size: 16
  num_epochs: 100
  learning_rate: 1.0e-4
  weight_decay: 0.0
  
  # Optimizer settings
  optimizer: "adam"
  optimizer_params:
    betas: [0.9, 0.999]
    eps: 1.0e-8
  
  # Learning rate scheduler
  scheduler: "reduce_on_plateau"
  scheduler_params:
    mode: "min"
    factor: 0.5
    patience: 10
    min_lr: 1.0e-6
  
  # Early stopping
  early_stopping: true
  patience: 20
  min_delta: 1.0e-4
  
  # Checkpointing
  save_best: true
  checkpoint_frequency: 10
  
  # Hardware
  device: "cuda"
  num_workers: 4
  pin_memory: true
  
  # Model-specific settings
  hidden_layers: [64, 128, 128, 64]
  activation: "tanh"
  num_pde_points: 10000
  num_bc_points: 1000
  
  # Loss weights
  pde_weight: 1.0
  bc_weight: 1.0
  data_weight: 1.0

# Data configuration
data:
  data_dir: "data/raw"
  output_dir: "data/processed"
  val_split: 0.1
  test_split: 0.1
  
  # Preprocessing
  normalize: true
  stats_file: "data/processed/statistics.npz"
  
  # Augmentation
  use_augmentation: true
  augmentation_factor: 2
  
  # Transforms
  crop_size: [256, 256]
  use_flips: true
  
  # Cache settings
  cache_size: 100
  prefetch_factor: 2

# Logging configuration
use_wandb: true
wandb_project: "navierflow"
log_frequency: 10

# Output configuration
output_dir: "outputs"
save_predictions: true
export_format: "h5"

# Simulation parameters
simulation:
  # Time stepping
  time_step: 0.001
  max_time: 10.0
  save_interval: 0.1
  
  # Mesh parameters
  mesh:
    type: "structured"  # or "unstructured"
    dimensions: 2  # or 3
    resolution: [100, 100]  # [nx, ny] for 2D, [nx, ny, nz] for 3D
    
  # Physics parameters
  physics:
    # Fluid properties
    fluid:
      density: 1.0
      viscosity: 0.001
      thermal_conductivity: 0.6
      specific_heat: 4186.0
      
    # Boundary conditions
    boundaries:
      velocity:
        type: "no-slip"  # or "slip", "periodic"
        value: [0.0, 0.0]  # [u, v] for 2D, [u, v, w] for 3D
      temperature:
        type: "dirichlet"  # or "neumann", "periodic"
        value: 293.15  # Kelvin
      pressure:
        type: "neumann"  # or "dirichlet", "periodic"
        value: 101325.0  # Pascal
        
    # Initial conditions
    initial:
      velocity: [0.0, 0.0]  # [u, v] for 2D, [u, v, w] for 3D
      temperature: 293.15  # Kelvin
      pressure: 101325.0  # Pascal
      
# Solver parameters
solver:
  # Linear solver
  linear:
    type: "gmres"  # or "bicgstab", "cg"
    tolerance: 1e-6
    max_iterations: 1000
    preconditioner: "ilu"  # or "jacobi", "none"
    
  # Nonlinear solver
  nonlinear:
    type: "newton"  # or "picard"
    tolerance: 1e-6
    max_iterations: 50
    
# Output parameters
output:
  # File formats
  formats:
    - "vtk"
    - "csv"
    - "hdf5"
    
  # Visualization
  visualization:
    enabled: true
    style: "modern"  # or "classic"
    colormap: "viridis"  # or "plasma", "inferno", "magma"
    show_mesh: false
    save_figures: true
    
  # Logging
  logging:
    level: "INFO"  # or "DEBUG", "WARNING", "ERROR"
    file: "simulation.log"
    console: true
    
# Performance parameters
performance:
  # Parallel computing
  parallel:
    enabled: true
    num_threads: 4
    num_processes: 1
    
  # Memory management
  memory:
    max_ram: 8192  # MB
    cache_size: 1024  # MB
    
  # Optimization
  optimization:
    level: 2  # 0-3
    vectorization: true
    openmp: true 